C#/SystemMagazynowyGUI/SystemMagazynowyMVC/Models/ErrorViewModel.cs
namespace SystemMagazynowyMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

C#/SystemMagazynowyGUI/SystemMagazynowyMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using SystemMagazynowyMVC.Models;

namespace SystemMagazynowyMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C#/SystemMagazynowyGUI/SystemMagazynowyMVC/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SystemMagazynowyMVC.Services;

namespace SystemMagazynowyMVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly IBasketService basketService;

        public OrderController(IBasketService basketService)
        {
            this.basketService = basketService;
        }

        public IActionResult Index()
        {
            return View(basketService.Towary.OrderBy(x => x.Nazwa).ToList());
        }

        public IActionResult RemoveFromBasket(int id)
        {
            var towar = basketService.Towary.FirstOrDefault(x => x.Id == id);
            if (towar == null)
            {
                return NotFound("Towar not found");
            }

            basketService.Remove(towar);
            return RedirectToAction("Index");
        }
    }
}

C#/SystemMagazynowyGUI/SystemMagazynowyMVC/Controllers/TowaryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shared;
using SystemMagazynowyMVC.Data;
using SystemMagazynowyMVC.Services;

namespace SystemMagazynowyMVC.Controllers
{
    public class TowaryController : Controller
    {
        private readonly DataContext context;
        private readonly IBasketService basketService;

        public TowaryController(DataContext context, IBasketService basketService)
        {
            this.context = context;
            this.basketService = basketService;
        }

        public async Task<IActionResult> Index()
        {
            var towary = await context.Towary.ToListAsync();
            return View(towary);
        }

        public async Task<IActionResult> AddToBasket(int id)
        {
            var towar = await context.Towary.FirstOrDefaultAsync(x => x.Id == id);
            if (towar == null)
            {
                return NotFound("Towar not found");
            }

            basketService.Add(towar);
            return RedirectToAction("Index");
        }
    }
}

C#/SystemMagazynowyGUI/SystemMagazynowyMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

C#/SystemMagazynowyGUI/SystemMagazynowyMVC/Views/Order/Index.cshtml
@model List<Towar>

<table class="table table-stripped">
    <tr>
        <th>Nazwa</th>
        <th>Typ</th>
        <th></th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.Nazwa</td>
            <td>@item.Typ</td>
            <td><a asp-controller="Order" asp-action="RemoveFromBasket" asp-route-id="@item.Id" class="btn btn-primary">Usuń</a></td>
        </tr>
    }
</table>

C#/SystemMagazynowyGUI/SystemMagazynowyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SystemMagazynowyMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SystemMagazynowyMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SystemMagazynowyMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Towary" asp-action="Index">Towary</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Koszyk</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SystemMagazynowyMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

C#/SystemMagazynowyGUI/SystemMagazynowyMVC/Views/Towary/Index.cshtml
@model List<Towar>?

<table class="table table-stripped">
    <tr>
        <th>Nazwa</th>
        <th>Typ</th>
        <th></th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.Nazwa</td>
            <td>@item.Typ</td>
            <td><a asp-controller="Towary" asp-action="AddToBasket" asp-route-id="@item.Id" class="btn btn-primary">Dodaj</a></td>
        </tr>
    }
</table>